### PR TITLE
Fix bidirectional arrow rendering in SVG files

### LINKED ISSUE #38: Fix visual representation of bidirectional arrows in SVG
Bidirectional arrows in the SVG files can look different between different cards. It might be related to the position of the cards or the bezier path, but some keep the desired dashes and others show more of a smooth line.

We want all bidirectional arrows to be dashed.

Image

### PR DESCRIPTION
**Pull request by jessicabran**
Resolves #38 

Adds a check for bidirectional arrows to prevent rendering a bidirectional arrow as two unidirectional arrows.

### CODE REVIEW

File: patterns-ts/src/visual/psvg/patternsvg.tsx [hunk 1]
```diff
@@ -31,16 +31,37 @@ export const PatternSVG = ({ pattern, config }: {
...
-          ))
+          Array.from(edgeMap.entries(), ([key, { edge, isBidirectional }]) => {
+            return (
+              <EdgeSVG
+                key={key}
+                edge={edge}
+                isBidirectional={isBidirectional}
+              />
+            );
+          })
```
Comment (sandervoerman) [inline patterns-ts/src/visual/psvg/patternsvg.tsx]:
```suggestion
          Array.from(edgeMap.entries(), ([key, { edge, isBidirectional }]) => (
            <EdgeSVG
              key={key}
              edge={edge}
              isBidirectional={isBidirectional}
            />
          ))
```

**Review by sandervoerman — CHANGES_REQUESTED** [review]
Looks good!

**Review by sandervoerman — APPROVED** [review]
Approved!
